name: "Terraform Destroy Azure Resources"

on:
  workflow_dispatch:   # 👈 Enables manual trigger from GitHub Actions UI
    inputs:
      confirm_destroy:
        description: "Type 'yes' to confirm Terraform destroy"
        required: true
        default: "no"

permissions:
  id-token: write       # Required for OIDC authentication
  contents: read

env:
  ARM_USE_OIDC: true
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  TF_IN_AUTOMATION: true

jobs:
  terraform-destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform-resources

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform init

      - name: Confirm Destroy Input
        id: confirm
        run: |
          if [ "${{ github.event.inputs.confirm_destroy }}" != "yes" ]; then
            echo "❌ Destroy not confirmed. Please type 'yes' to confirm destroy."
            exit 1
          else
            echo "✅ Destroy confirmed. Proceeding..."
          fi

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=tfplan

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
