name: "Terraform Apply / Destroy with Dynamic Backend"

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: true
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  TF_IN_AUTOMATION: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./resources

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init (Local Backend)
        run: terraform init

      - name: Terraform Apply Backend Storage
        run: terraform apply -auto-approve

      - name: Terraform Init (Remote Backend)
        run: |
          cat > backend.tf <<EOL
            terraform {
            backend "azurerm" {
            resource_group_name  = "tfstate-rg"
            storage_account_name = "${{ github.run_id }}sa"   # dynamically unique name
            container_name       = "tfstate"
            key                  = "terraform.tfstate"
                            }
                    }
            EOL
          terraform init -reconfigure

      - name: Terraform Plan / Apply / Destroy
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform plan -out=tfplan
            terraform apply -auto-approve tfplan
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            terraform plan -destroy -out=tfplan
            terraform destroy -auto-approve
          else
            echo "Invalid action"
            exit 1
          fi
