# .github/workflows/terraform-manual.yml

name: "Terraform Apply / Destroy"

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Select Terraform action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy
      confirm_destroy:
        description: "Type 'yes' to confirm Terraform destroy"
        required: false
        default: "no"

permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: true
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  TF_IN_AUTOMATION: true

jobs:
  terraform:
    name: "Terraform Action"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform-resources

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan / Destroy Logic
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            echo "✅ Applying Terraform..."
            terraform plan -out=tfplan
            terraform apply -auto-approve tfplan
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            if [ "${{ github.event.inputs.confirm_destroy }}" != "yes" ]; then
              echo "❌ Destroy not confirmed. Type 'yes' to confirm."
              exit 1
            fi
            echo "⚠️ Destroying Terraform resources..."
            terraform plan -destroy -out=tfplan
            terraform destroy -auto-approve
          else
            echo "❌ Invalid action selected: ${{ github.event.inputs.action }}"
            exit 1
          fi
